name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Release src
    - name: Pack
      if: github.ref == 'refs/heads/master'
      run: dotnet pack -c Release --no-build --include-source src
    - name: Publish the package to nuget.org
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push src/*/bin/Release/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.STEP_EXTENSIONS_NUGET_API }}

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Release src
    - name: Test
      run: dotnet test --no-build --verbosity normal